
<?php
$url_order = 'ASC';
if ($order_by == 'tire_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'tire_serie')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_position')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_cost')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_status')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'tire_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH VỎ LỐP </h1></center>
<div id="content" style="padding:5px;">
<?php if ($_SESSION['role_logined'] != 7 ) { ?>     
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm thông tin vỏ</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('tire/import')?>">Import Excel</a>
</div>
<?php } ?>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <a class="add_button" id="report_excel" href="<?= $this->url('tire/report')?>">Thống kê</a>
        </div>
        <?php if ($_SESSION['role_logined'] != 7 ) { ?>
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
        <?php } ?>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

   
</div>

<table class="table_data">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'tire_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_name','<?php echo $url_order ?>')">Thương hiệu <?php if ($order_by == 'tire_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_serie','<?php echo $url_order ?>')">Số serie <?php if ($order_by == 'tire_serie'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_position','<?php echo $url_order ?>')">Vị trí <?php if ($order_by == 'tire_position'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_cost','<?php echo $url_order ?>')">Giá  <?php if ($order_by == 'tire_cost'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','tire_status','<?php echo $url_order ?>')">Trạng thái  <?php if ($order_by == 'tire_status'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <?php if ($_SESSION['role_logined'] != 7 ) { ?>   
        <th  class="fix">&nbsp;</th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($tires as $tire) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire->tire_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $tire->tire_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" id="tire_name_<?php echo $tire->tire_id; ?>"><?php echo $tire->tire_name; ?></td>
            <td class="fix" id="tire_serie_<?php echo $tire->tire_id; ?>"><?php echo $tire->tire_serie; ?></td>
            <td class="fix" data="<?php echo $tire->tire_position; ?>" id="tire_position_<?php echo $tire->tire_id; ?>"><?php echo $tire->tire_position==1?"Đầu":"Mooc"; ?></td>
            <td class="fix" id="tire_cost_<?php echo $tire->tire_id; ?>"><?php echo $lib->formatMoney($tire->tire_cost); ?></td>
            <td class="fix" data="<?php echo $tire->tire_status; ?>" id="tire_status_<?php echo $tire->tire_id; ?>"><?php echo $tire->tire_status==0?"Hư":($tire->tire_status==1?"Đang sử dụng":($tire->tire_status==2?"Dự phòng":"Đã bán")); ?></td>
            <?php if ($_SESSION['role_logined'] != 7 ) { ?>
            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $tire->tire_id ?>)" >Xóa</a>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin vỏ lốp</h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_tire" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm thông tin vỏ</a></div></td>
                            
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Số serie </td>
                            <td>
                                <input type="text" autofocus id="tire_serie" name="tire_serie" tabindex="1" required="required">
                            </td>
                            <td>Giá </td>
                            <td><input type="text" id="tire_cost" class="number" name="tire_cost" tabindex="4" ></td>
                            
                            <td>Thương hiệu </td>
                            <td><input type="text" id="tire_name" name="tire_name" tabindex="6" ></td>

                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Vị trí </td>
                            <td>
                                <input type="radio" checked  name="tire_position" tabindex="2" value="1"> Đầu
                                <input type="radio"  name="tire_position"  value="2"> Mooc
                            </td>
                            <td>Trạng thái </td>
                            <td>
                                <select style="width:150px" id="tire_status" name="tire_status" tabindex="5" >
                                    <option value="2">Dự phòng</option>
                                    <option value="1">Đang sử dụng</option>
                                    <option value="0">Hư</option>
                                    <option value="3">Đã bán</option>
                                </select>
                            </td>
                            
                        </tr>
                        
                        
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                            </td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="7"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="8"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>

<?php if ($_SESSION['role_logined'] != 7 ) { ?>
<script type="text/javascript">
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   
});
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        
        var tire_serie = $(this).find("#tire_serie_"+$(this).attr('id')).text();
        var tire_position = $(this).find("#tire_position_"+$(this).attr('id')).attr('data');
        var tire_cost = $(this).find("#tire_cost_"+$(this).attr('id')).text();
        var tire_status = $(this).find("#tire_status_"+$(this).attr('id')).attr('data');
        var tire_name = $(this).find("#tire_name_"+$(this).attr('id')).text();
        //alert(tire_from);
        $('#yes').val($(this).attr('id'));
        
        $('#tire_name').val(tire_name);
        $('#tire_serie').val(tire_serie);
        $('#tire_cost').val(tire_cost);
        var radioLength = $("input[name='tire_position']").length;
        for(var i = 0; i < radioLength; i++) {
            $("input[name='tire_position']")[i].checked = false;
            if($("input[name='tire_position']")[i].value == tire_position) {
                $("input[name='tire_position']")[i].checked = true;
            }
        }

        $('#tire_status option[value='+tire_status+']').attr('selected','selected');
        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

        $('#tire_serie').focus();
        $('#tire_cost').val(0);
        $('#tire_name').val("");
        $("input[name='tire_position'][value='1']").attr('checked',true);
        $('#tire_status option[value=2]').attr('selected','selected');
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


}


$(document).ready(function(){
            // Validate form
            $("#add_tire").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    
                
                    var tire_serie = $('#tire_serie').attr('value');
                    var tire_cost = $('#tire_cost').attr('value');
                    var tire_position = $('input[name=tire_position]:checked').val();
                    var tire_status = $('#tire_status').attr('value');
                    var tire_name = $('#tire_name').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/tire/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            tire_serie: tire_serie,
                            tire_cost: tire_cost,
                            tire_position: tire_position,
                            tire_status: tire_status,
                            tire_name: tire_name,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Vỏ này đã tồn tại") {
                                    $('#tire_serie_'+yes).text(tire_serie);
                                    $('#tire_cost_'+yes).text(tire_cost);
                                    $('#tire_position_'+yes).text(tire_position==1?"Đầu":"Mooc");
                                    $('#tire_status_'+yes).text(tire_status==0?"Hư":(tire_status==1?"Đang sử dụng":(tire_status==2?"Dự phòng":"Đã bán")));
                                    $('#tire_name_'+yes).text(tire_name);
                                }
                            }
                            else{
                                if (answer.trim() != "Vỏ này đã tồn tại") {
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="tire_name_'+parseInt(lastID+1)+'">'+tire_name+'</td><td class="fix" id="tire_serie_'+parseInt(lastID+1)+'">'+tire_serie+'</td><td class="fix" id="tire_position_'+parseInt(lastID+1)+'">'+(tire_position==1?"Đầu":"Mooc")+'</td><td class="fix" id="tire_cost_'+parseInt(lastID+1)+'">'+tire_cost+'</td><td class="fix" id="tire_status_'+parseInt(lastID+1)+'">'+(tire_status==0?"Hư":(tire_status==1?"Đang sử dụng":(tire_status==2?"Dự phòng":"Đã bán")))+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   
   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<?php } ?>

<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

    $("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:200,
            width:500,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>
</div>