
<?php


    $i = 1;

?>

<div id="loading"></div>
<div id="winpopup"></div>
<center style="clear:both;margin-bottom: 20px;"><h1> THỐNG KÊ VỎ LỐP </h1></center>

<div id="content" style="padding:5px;">
<table class="table_data">
<thead>
    <tr>
    	
        <th rowspan="2" class="fix">
            <a >STT </a>
        </th>
        <th  class="fix">
            <a >Thương hiệu </a>
        </th>
        <th  class="fix">
            <a >Đang sử dụng </a>
        </th>
        <th  class="fix">
            <a >Hư </a>
        </th>
        <th  class="fix">
            <a >Dự phòng  </a>
        </th>
        <th  class="fix">
            <a >Đã bán  </a>
        </th>
        <th  class="fix">
            <a >Tổng cộng  </a>
        </th>
           
    </tr>
    
   </thead>
   <tbody>
    <?php $tongcong=0; $tong_sd=0; $tong_hu=0; $tong_duphong=0; $tong_ban=0; $daban=0; ?>
    <?php foreach ($tires as $tire) : ?>
    <?php if ($tire->tire_name=="CSMNA") {
        $daban = 70;
    } 
    else{
        $daban = 0;
    }
    ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $tire->tire_id ?>" class="edit_tr">
            <td class="fix"><?php echo $i++; ?></td>
            <td class="fix" ><?php echo $tire->tire_name; ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($tires_data[$tire->tire_name]['tire_sd'])?$tires_data[$tire->tire_name]['tire_sd']:0); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($tires_data[$tire->tire_name]['tire_hu'])?$tires_data[$tire->tire_name]['tire_hu']:0); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney(isset($tires_data[$tire->tire_name]['tire_duphong'])?$tires_data[$tire->tire_name]['tire_duphong']:0); ?></td>
            <td class="fix" ><?php echo $lib->formatMoney((isset($tires_data[$tire->tire_name]['tire_ban'])?$tires_data[$tire->tire_name]['tire_ban']:0)+$daban); ?></td>
            <td class="fix" >
                <?php echo $lib->formatMoney((isset($tires_data[$tire->tire_name]['tire_ban'])?$tires_data[$tire->tire_name]['tire_ban']:0)+$daban+(isset($tires_data[$tire->tire_name]['tire_sd'])?$tires_data[$tire->tire_name]['tire_sd']:0)+(isset($tires_data[$tire->tire_name]['tire_hu'])?$tires_data[$tire->tire_name]['tire_hu']:0)+(isset($tires_data[$tire->tire_name]['tire_duphong'])?$tires_data[$tire->tire_name]['tire_duphong']:0)); ?>
            </td>
            
        </tr>
        <?php
            $tong_sd += isset($tires_data[$tire->tire_name]['tire_sd'])?$tires_data[$tire->tire_name]['tire_sd']:0;
            $tong_hu += isset($tires_data[$tire->tire_name]['tire_hu'])?$tires_data[$tire->tire_name]['tire_hu']:0;
            $tong_duphong += isset($tires_data[$tire->tire_name]['tire_duphong'])?$tires_data[$tire->tire_name]['tire_duphong']:0;
            $tong_ban += isset($tires_data[$tire->tire_name]['tire_ban'])?$tires_data[$tire->tire_name]['tire_ban']:0;
            $tong_ban += $daban;
        ?>

    <?php endforeach; ?>
    <?php $tongcong = $tong_sd+$tong_hu+$tong_duphong+$tong_ban; ?>
        <tr  style="font-weight: bold; color: rgb(23, 119, 226);" >
            
            <th colspan="2" style="border-right: 1px solid rgb(236, 235, 235);border-top: 1px solid #80C8E5;padding: 7px; text-align: right;" >
                Tổng cộng
            </th>
            <td class="fix " ><?php echo $lib->formatMoney($tong_sd) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tong_hu) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tong_duphong) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tong_ban) ?></td>
            <td class="fix " ><?php echo $lib->formatMoney($tongcong) ?></td>
           
        </tr>

   </tbody>
</table>



</div>