<div id="content" style="padding:5px">
<center style="margin-bottom: 10px;"><h1> KẾT QUẢ HOẠT ĐỘNG CỦA VỎ LỐP </h1></center>


<?php 
$tongthu = 0;
$tongkm = 0;
$tongtyle = 0;
$dem = 0;
?>


<div class="report">
    <div class="report-left">
        <table class="table_data">
            <thead>
                <tr>
                    <th class="fix">TT</th>
                    <th class="fix">Nội dung</th>
                </tr>
           </thead>
           <tbody>
                
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    <td style="text-align:center;" class="fix">I</td>
                    <td class="fix">Doanh thu</td>
                </tr>
                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    <td style="text-align:center;" class="fix">II</td>
                    <td class="fix">Tỉ lệ % doanh thu</td>
                </tr>
                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    <td style="text-align:center;" class="fix">III</td>
                    <td class="fix">Số km đã chạy</td>
                </tr>
                
                
           </tbody>
        </table>
    </div>
    <div class="report-right">
    <div class="report-right report-right-fix" style="float:left">
        <table class="table_data">
            <thead>
                <tr>
                    <th></th>
                    <?php foreach ($tires as $tire): 
                    if (isset($doanhthu[$tire->tire_name] )) {
                        $dem++;
                    }
                    ?>
                    <th class="fix"><?php echo $tire->tire_name ?></th>
                    <?php endforeach; ?>
                </tr>
           </thead>
           <tbody>
                
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    <td></td>
                    <?php foreach ($tires as $tire): $tongthu += isset($doanhthu[$tire->tire_name])?$doanhthu[$tire->tire_name]:0; ?>
                    <td class="fix"><?php echo $lib->formatMoney(isset($doanhthu[$tire->tire_name])?$doanhthu[$tire->tire_name]:0) ?></td>
                    <?php endforeach; ?>
                </tr>
                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    <td></td>
                    <?php foreach ($tires as $tire):  $tongtyle += (isset($doanhthu[$tire->tire_name] )? round(($tongvo[$tire->tire_name]*$tire->tire_cost)/$doanhthu[$tire->tire_name],2):0); ?>
                    <td title="" class="fix "><?php echo  (isset($doanhthu[$tire->tire_name] )? round(($tongvo[$tire->tire_name]*$tire->tire_cost)/$doanhthu[$tire->tire_name],2):0).' %'; ?></td>
                    <?php endforeach; ?>
                </tr>
                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    <td></td>
                    <?php foreach ($tires as $tire): $tongkm += isset($km[$tire->tire_name])?$km[$tire->tire_name]:0 ; ?>
                    <td title="" class="fix "><?php echo $lib->formatMoney(isset($km[$tire->tire_name])?$km[$tire->tire_name]:0) ?></td>
                    <?php endforeach; ?>
                </tr>
                
                
                
           </tbody>
        </table>
    </div>

    <div style="width:150px; float:right; ">
        <table class="table_data">
            <thead>
                <tr>
                    
                    <th class="fix">Cộng</th>
                </tr>
           </thead>
           <tbody>
                
                <tr style=" color:rgb(0, 32, 96); font-weight:bold;">
                    
                    
                    <td class="fix"><?php echo $lib->formatMoney($tongthu) ?></td>
                    
                </tr>

                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    
                    <td title="" class="fix "><?php echo ($tongtyle>0?round($tongtyle/$dem,2):0).' %'; ?></td>
                    
                </tr>
                <tr style=" color:rgb(0, 32, 96); font-style: italic; font-weight:bold;">
                    
                    <td title="" class="fix "><?php echo $lib->formatMoney($tongkm) ?></td>

                </tr>
                
                
           </tbody>
        </table>
    </div>
</div>
</div>

<script type="text/javascript">
    $(function() {

        var w = $(".report").width();

      $(".report-right-fix").width(w-375);


              
            
    
});



</script>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
    .table_data tbody tr td.fix{
        min-width: 180px;
    }
.table_data tbody tr td.fix:nth-child(1){
        min-width: 30px;
    }
.report{
    width: 100%;
    margin: -5px auto;
}
.report-left{
    float: left;
    width: 200px;
    margin-right:25px;
}
.report-right{
    
    overflow: auto;
}
.showtooltip {
        display:none;
        position:absolute;
        border:1px solid #333;
        background-color:#161616;
        border-radius:5px;
        padding:10px;
        color:#fff;
        font-size:12px Arial;
    }
</style>
<script type="text/javascript">
$(document).ready(function() {
// Tooltip only Text
$('.masterTooltip').hover(function(){
        // Hover over code
        var title = $(this).attr('title');
        $(this).data('tipText', title).removeAttr('title');
        $('<p class="showtooltip"></p>')
        .text(title)
        .appendTo('body')
        .fadeIn('slow');
}, function() {
        // Hover out code
        $(this).attr('title', $(this).data('tipText'));
        $('.showtooltip').remove();
}).mousemove(function(e) {
        var mousex = e.pageX + 20; //Get X coordinates
        var mousey = e.pageY + 10; //Get Y coordinates
        $('.showtooltip')
        .css({ top: mousey, left: mousex })
});


});

var w = $("#container").width();

      $(".container").width(w);
      $(".navbar-inner").width(w);
      $(".navbar").width(w);

$(document).ready(function() {
    function fixDiv() {
      
      var $cache = $('.navbar-fixed-top'); 
      if ($(window).scrollTop() > 42) {
        $cache.css({'position': 'fixed', 'top': '0'}); 
        $(".navbar-inner").css({'width':'100%'});
        $(".navbar").css({'width':'100%'});
      }
      else{
        var w = $("#container").width();
        $cache.css({'position': 'relative', 'top': 'auto'});
        $(".navbar-inner").width(w);
        $(".navbar").width(w);
      }
      
    }
  $(window).scroll(fixDiv);
  fixDiv();
});
</script>
</div>