
<?php
$url_order = 'ASC';
if ($order_by == 'task_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'work_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'work_date')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'username')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'status')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'time_work')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'time_end')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<center style="clear:both;margin-bottom: -30px;"><h1> CÔNG VIỆC </h1></center>
<div id="content" style="padding:5px;">

<?php if($_SESSION['role_logined'] == 1){ ?>  
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm bảng công việc</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('task/import')?>">Import Excel</a>
    
</div>
<?php } ?>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    
 <div class="tablenav top">
        <div class="alignleft">
            <a class="add_button report_task" href="<?php echo $this->url('task/report/'.$staff.'/'.strtotime($batdau).'/'.strtotime($ketthuc)) ?>">Thống kê</a>
        </div>
        <div class="add-box">
                  
            Từ  <input style="width:100px" type="search" name="batdau" id="batdau" placeholder="Chọn ngày" <?php if(isset($batdau)) echo "value='$batdau'"; ?> >  
            Đến  <input style="width:100px" type="search" name="ketthuc" id="ketthuc" placeholder="Chọn ngày" <?php if(isset($ketthuc)) echo "value='$ketthuc'"; ?> >  
             <input type="button" name="xem" id="xem" value="Xem" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
            
        </div>
    </div>
    <div class="tablenav top">
        <div style="clear:both"></div>
        
        <div class="add-box">
            <input type="button" name="chon" id="chon" value="Chọn" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">  
        </div>
        
        <div class="add-box" style="margin-right: 5px">

        
           
            <select name="sl_trangthai" id="sl_trangthai">
                <option selected="selected" value="">Trạng thái</option>
                
                <option value="1">Đã hoàn thành</option>
                <option value="0">Chưa hoàn thành</option>
                
            </select>
            
        </div>
        <div class="add-box" style="margin-right: 5px">

            
            <select name="sl_staff" id="sl_staff">
                <option selected="selected" value="">Nhân viên</option>
                <?php if($_SESSION['role_logined'] == 1){ ?>
                <?php foreach ($staffs as $sm) { ?>
                <option value="<?php echo $sm->user_id ?>"><?php echo $sm->username ?></option>
                <?php } }?>
            </select>
           
            
        </div>
        
        <div class="alignleft actions">
            <select name="action" id="action">
                <option value="-1" selected="selected">Chọn</option>
                <?php if($_SESSION['role_logined'] == 1){ ?>
                <option value="delete">Xóa</option>
                <?php } ?>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
        </div>
        <div class="alignleft actions">
        <select name="m" id="chonloc">
            <option  value="18446744073709">Hiển thị tất cả</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="20">Hiển thị 20 giá trị</option>
            <option value="30">Hiển thị 30 giá trị</option>
            <option selected="selected" value="50">Hiển thị 50 giá trị</option>
        </select>
        <input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">                               
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_date','<?php echo $url_order ?>')">Ngày <?php if ($order_by == 'work_date'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','work_name','<?php echo $url_order ?>')">Công việc <?php if ($order_by == 'work_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','username','<?php echo $url_order ?>')">Người thực hiện <?php if ($order_by == 'username'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','time_work','<?php echo $url_order ?>')">Thời gian yêu cầu <?php if ($order_by == 'time_work'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','time_end','<?php echo $url_order ?>')">Thời gian hoàn thành <?php if ($order_by == 'time_end'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','status','<?php echo $url_order ?>')">Trạng thái <?php if ($order_by == 'status'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
           
        <th  class="fix">&nbsp;</th>
    </tr>
    
   </thead>
   <tbody>
    <?php $v = array(); $doanhthu = array(); $chiphi = array(); $loinhuan = array(); $litdau = array(); ?>
    <?php foreach ($tasks as $task) : ?>
    
    
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');"  id="<?php echo $task->task_id ?>" class="edit_tr">
        	<td>
                <input name="check[]" type="checkbox" class="checkbox" value="<?php echo $task->task_id ?>">
                
            </td>
            <td class="fix" id="work_date_<?php echo $task->task_id; ?>"><?php echo $lib->hien_thi_ngay_thang($task->work_date); ?></td>
            <td nowrap class="fix" data="<?php echo $task->work; ?>" id="work_<?php echo $task->task_id; ?>"><?php echo $task->work_name ?></td>
            <td class="fix" data="<?php echo $task->assigned; ?>" id="assigned_<?php echo $task->task_id; ?>"><?php echo $task->username; ?></td>
            <td class="fix" data="<?php echo $task->time_work; ?>"  id="time_work_<?php echo $task->task_id; ?>"><?php echo date('H:i', mktime(0,$task->time_work)); ?></td>
            <td class="fix"  id="time_end_<?php echo $task->task_id; ?>"><?php echo date('H:i', mktime(0,$task->time_end)); ?></td>
            <td class="fix" data="<?php echo $task->status; ?>" id="status_<?php echo $task->task_id; ?>"><?php echo $task->status==1?"Đã hoàn thành":"Chưa hoàn thành"; ?></td>
            
            <td>
                <?php if($_SESSION['role_logined'] == 1){ ?>
                <a class="view_task" href="<?php echo $this->url('task/view/'.$task->task_id) ?>">Chi tiết</a>
                |
                <a class="error" onclick="del(<?php echo $task->task_id ?>)" >Xóa</a>
                <?php } ?>
            </td>
        </tr>

        
            

    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>
<?php if($_SESSION['role_logined'] == 1){ ?>
<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Bảng công việc</h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_task" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm bảng công việc</a></div></td>
                            
                        </tr>
                        <tr>
                            <td>Ngày </td>
                            <td><input type="text"  id="work_date" name="work_date" tabindex="1" required="required"></td>
                            <td>Công việc</td>
                            <td>
                                
                                <textarea id="work" name="work" tabindex="2" required="required" >
                                    
                                </textarea>
                                <ul id="work_list_id"></ul>
                            </td>
                            <td>Thời gian yêu cầu </td>
                            <td>
                                <input style="width: 30px" type="text" id="time_work_hour" placeholder="Giờ" class="number" name="time_work_hour" tabindex="3" required="required">
                                <input style="width: 30px" type="text" id="time_work_minute" placeholder="Phút" class="number" name="time_work_minute" tabindex="4" required="required">
                            </td>
                            <td>Người thực hiện </td>
                            <td><input type="text"  id="assigned" name="assigned" tabindex="5" required="required" >
                                <ul id="staff_list_id"></ul>
                            </td>

                        </tr>
                        
                        
                        
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="6"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="7"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>
<script type="text/javascript">
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   $('#work_list_id').slideUp(200);
   $('#staff_list_id').slideUp(200);
});
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        
        var work = $(this).find("#work_"+$(this).attr('id')).text();
        var work_date = $(this).find("#work_date_"+$(this).attr('id')).text();
        var assigned = $(this).find("#assigned_"+$(this).attr('id')).text();
        var time_work = $(this).find("#time_work_"+$(this).attr('id')).attr('data');
        
        //alert(task_from);
        $('#yes').val($(this).attr('id'));
        
        $('#work').val(work);
        $('#work_date').val(work_date);
        $('#assigned').val(assigned);

        var hour = Math.floor(time_work / 60);
        var minute = Math.round(((time_work / 60)-hour) * 60);
        

        $('#time_work_hour').val(hour);
        $('#time_work_minute').val(minute);
        

        $('#work').attr('data',$(this).find("#work_"+$(this).attr('id')).attr('data'));
        
        $("#work").attr("code",'true');

        $('#assigned').attr('data',$(this).find("#assigned_"+$(this).attr('id')).attr('data'));
        
        $("#assigned").attr("code",'true');
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

        $('#work').focus();
        
        $('#work_date').val("");
        
        $('#assigned').val("");
        

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });

        $("#work").attr("code",'false');
        $('#work').val("");
        $("#assigned").attr("code",'false');
        $('#assigned').val("");

}


$(document).ready(function(){
            // Validate form
            $("#add_task").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    
                    if ($('#assigned').attr('code') == 'false') {
                        $('#assigned').val("");
                        $('#assigned').focus();
                        return false;
                    };
                
                    var work = $('#work').attr('data');
                    var assigned = $('#assigned').attr('data');
                    var work_date = $('#work_date').attr('value');
                    var hour = $('#time_work_hour').attr('value');
                    var minute = $('#time_work_minute').attr('value');
                    var time_work = (parseInt(hour)*60)+parseInt(minute);
                    

                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/task/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            work: work,
                            assigned: assigned,
                            work_date: work_date,
                            time_work: time_work,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            //alert(answer);
                            
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    $('#work_date_'+yes).text(work_date);
                                    $('#work_'+yes).text($('#work').val());
                                    $('#assigned_'+yes).text($('#assigned').val());
                                    $('#time_work_'+yes).text(hour+':'+minute);
                                }
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="work_date_'+parseInt(lastID+1)+'">'+work_date+'</td><td class="fix" id="work_'+parseInt(lastID+1)+'">'+$( "#work" ).val()+'</td><td class="fix" id="time_work_'+parseInt(lastID+1)+'">'+(hour+':'+minute)+'</td><td class="fix" id="time_end_'+parseInt(lastID+1)+'"></td><td class="fix" id="status_'+parseInt(lastID+1)+'">Chưa hoàn thành</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));

                                }
                            }

                            
                            
                        }
                    });
                    return false;
                     
                 }
            });
   



   $('#work').keyup(function(){
        $("#work").attr("data","");
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/task/getwork',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                
                if (data.trim() == "") {
                    $('#work_list_id').slideUp(200);
                }
                else{
                    $('#work_list_id').slideDown(200);
                    $('#work_list_id').html(data);
                }
            }
        });
        if ($('#work').val() == "" || $('#work').attr('data') == "") {
            //$('#loc_from').val("");
            $('#work').attr('data',"");
            $('#work').attr('code',false);
        }
      
   });
   $('#assigned').keyup(function(){
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/task/getstaff',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                    $('#staff_list_id').slideDown(200);
                    $('#staff_list_id').html(data);
                
                
            }
        });
        if ($('#assigned').val() == "" || $('#assigned').attr('data') == "") {
            //$('#loc_from').val("");
            $('#assigned').attr('data',"");
            $('#assigned').attr('code',false);
        }
      
   });
   



   
   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}
function set_item_work(value,name,time) {
    // change input value
    $('#work').val(name);
    $("#work").attr("data",value);
    $("#work").attr("code",'true');

    var hour = Math.floor(time / 60);
    var minute = Math.round(((time / 60)-hour) * 60);
    $('#time_work_hour').val(hour);
    $('#time_work_minute').val(minute);
    
    // hide proposition list
    $('#work_list_id').hide();
    $('#work').focus();

}
function set_item_staff(value,name) {
    // change input value
    $('#assigned').val(name);
    $("#assigned").attr("data",value);
    $("#assigned").attr("code",'true');
    
    // hide proposition list
    $('#staff_list_id').hide();
    $('#assigned').focus();

}
</script>

<div style="display:none" id="lasted"></div>

<?php } ?>

<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

    $("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:200,
            width:500,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

    $(".view_task").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:$(window).height()-80,
            width:$(window).width()-80,
            resizable: true,
            title:'Chi tiết công việc',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

    $(".report_task").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:$(window).height()-80,
            width:$(window).width()-80,
            resizable: true,
            title:'Thống kê công việc',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

    
</script>
</div>


<style type="text/css">
    .ui-dialog .ui-dialog-content{
        padding: 3px;
    }


</style>



<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
         
    };  
    $("#work_date").datepicker(pickerOpts);

    
              
            
    
});



</script>



<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>
<script type="text/javascript">
    $(function() {
    var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#ketthuc" ).datepicker( "option", "minDate", selectedDate );

         },
         
    };  
    $("#batdau").datepicker(pickerOpts);

    var pickerOpts4 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6",
        "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm",
        "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5",
        "T6", "T7"],
        //defaultDate: "+1w",
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd-mm-yy',
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#batdau" ).datepicker( "option", "maxDate", selectedDate );
                
         },
         
    };  
    $("#ketthuc").datepicker(pickerOpts4);
              
            
    
});

var x = "<?php echo $staff ?>";
$('#sl_staff option[value='+x+']').attr('selected','selected');

var tt = "<?php echo $trangthai ?>";
$('#sl_trangthai option[value='+tt+']').attr('selected','selected');

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var w = $(".table_data").width();

      $(".container").width(w);
      $(".navbar-inner").width(w);
      $(".navbar").width(w);
      //$("#container").width(w);
</script>