
<?php
$url_order = 'ASC';
if ($order_by == 'driver_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'vehicle_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'driver_name')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'driver_phone')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'start_work')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'end_work')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';


    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<center style="clear:both;margin-bottom: -30px;"><h1> BÀN GIAO XE </h1></center>
<div id="content" style="padding:5px;">

<?php if ($_SESSION['role_logined'] != 7 ) { ?>    
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm tài xế</a>
</div>
<?php } ?>

	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <?php if ($_SESSION['role_logined'] != 7 ) { ?>
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
        <?php } ?>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'driver_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_code','<?php echo $url_order ?>')">Mã NV <?php if ($order_by == 'driver_code'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th nowrap class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_name','<?php echo $url_order ?>')">Tên tài xế <?php if ($order_by == 'driver_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_birth','<?php echo $url_order ?>')">Ngày sinh <?php if ($order_by == 'driver_birth'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_cmnd','<?php echo $url_order ?>')">CMND <?php if ($order_by == 'driver_cmnd'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_phone','<?php echo $url_order ?>')">SĐT <?php if ($order_by == 'driver_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_bank','<?php echo $url_order ?>')">TK<?php if ($order_by == 'driver_bank'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vehicle_number','<?php echo $url_order ?>')">Số xe <?php if ($order_by == 'vehicle_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','start_work','<?php echo $url_order ?>')">Ngày nhận xe <?php if ($order_by == 'start_work'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','end_work','<?php echo $url_order ?>')">Ngày trả xe <?php if ($order_by == 'end_work'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <?php if ($_SESSION['role_logined'] != 7 ) { ?>
           
        <th  class="fix">&nbsp;</th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($drivers as $driver) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $driver->driver_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $driver->driver_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            
            <td class="fix" id="driver_code_<?php echo $driver->driver_id; ?>"><?php echo $driver->driver_code; ?></td>
            <td class="fix" id="driver_name_<?php echo $driver->driver_id; ?>"><?php echo $driver->driver_name; ?></td>
            <td class="fix" id="driver_birth_<?php echo $driver->driver_id; ?>"><?php echo $lib->hien_thi_ngay_thang($driver->driver_birth); ?></td>
            <td class="fix" id="driver_cmnd_<?php echo $driver->driver_id; ?>"><?php echo $driver->driver_cmnd; ?></td>
            <td class="fix" id="driver_phone_<?php echo $driver->driver_id; ?>"><?php echo $driver->driver_phone; ?></td>
            <td class="fix" id="driver_bank_<?php echo $driver->driver_id; ?>"><?php echo $driver->driver_bank; ?></td>
            <td class="fix" data="<?php echo $driver->vehicle ?>" id="vehicle_number_<?php echo $driver->driver_id; ?>"><?php echo $driver->vehicle_number; ?></td>
            <td class="fix" id="start_work_<?php echo $driver->driver_id; ?>"><?php echo $lib->hien_thi_ngay_thang($driver->start_work); ?></td>
            <td class="fix" id="end_work_<?php echo $driver->driver_id; ?>"><?php echo $lib->hien_thi_ngay_thang($driver->end_work); ?></td>
            <td style="display:none" class="fix" id="steersman_<?php echo $driver->driver_id; ?>"><?php echo $driver->steersman; ?></td>
            <?php if ($_SESSION['role_logined'] != 7 ) { ?>
            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $driver->driver_id ?>)" >Xóa</a>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin tài xế </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_driver" method="post" action="">
                      <table style="margin-top:0px;width:100%">
                        <tr>
                            
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm tài xế</a></div></td>
                            
                        </tr>
                        <tr>
                            <td>Tên tài xế </td>
                            <td>
                                <input type="text" autofocus autocomplete="off"   id="driver_name" name="driver_name" tabindex="1" required="required" placeholder="Nhập tên hoặc * để chọn" >
                                            <ul id="vehicle_list_id"></ul>
                            </td>
                            <td>Mã NV </td>
                            <td><input disabled type="text" id="driver_code"  name="driver_code" tabindex="2" required="required" ></td>
                            <td>Số CMND </td>
                            <td><input disabled type="text" id="driver_cmnd"  name="driver_cmnd" tabindex="3" required="required" ></td>
                            
                            

                        </tr>
                        <tr>
                            <td>Ngày sinh </td>
                            <td><input disabled class="ngay" type="text"   id="driver_birth" name="driver_birth" tabindex="4"  ></td>
                            <td>SĐT tài xế </td>
                            <td><input disabled type="text" class="numbers" id="driver_phone" name="driver_phone" tabindex="5" ></td>
                            <td>Số TK </td>
                            <td><input disabled type="text" id="driver_bank"  name="driver_bank" tabindex="6"  ></td>
                            

                        </tr>
                        <tr>
                            <td>Số xe </td>
                            <td>
                                <select style="width:120px" id="vehicle" name="vehicle" tabindex="7" required="required" >
                                    <?php foreach ($vehicles as $vehicle) { ?>
                                    <option value="<?php echo $vehicle->vehicle_id ?>"><?php echo $vehicle->vehicle_number ?></option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>Ngày nhận xe </td>
                            <td><input class="ngay" type="text"   id="start_work" name="start_work" tabindex="8" required="required" ></td>
                            <td>Ngày trả xe </td>
                            <td><input class="ngay" type="text"   id="end_work" name="end_work" tabindex="9" required="required" ></td>
                            
                        </tr>
                        
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="10"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="11"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>

<?php if ($_SESSION['role_logined'] != 7 ) { ?>
<script type="text/javascript">
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   
});
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        
        var driver_name = $(this).find("#driver_name_"+$(this).attr('id')).text();
        var driver_birth = $(this).find("#driver_birth_"+$(this).attr('id')).text();
        var driver_code = $(this).find("#driver_code_"+$(this).attr('id')).text();
        var driver_cmnd = $(this).find("#driver_cmnd_"+$(this).attr('id')).text();
        var driver_bank = $(this).find("#driver_bank_"+$(this).attr('id')).text();
        var driver_phone = $(this).find("#driver_phone_"+$(this).attr('id')).text();
        var vehicle_number = $(this).find("#vehicle_number_"+$(this).attr('id')).text();
        var start_work = $(this).find("#start_work_"+$(this).attr('id')).text();
        var end_work = $(this).find("#end_work_"+$(this).attr('id')).text();
        var steersman = $(this).find("#steersman_"+$(this).attr('id')).text();
        //alert(driver_from);
        $('#yes').val($(this).attr('id'));
        
        $('#driver_birth').val(driver_birth.replace(/\//g,"-"));
        $('#driver_name').val(driver_name);
        $('#driver_name').attr('data', steersman);
        $('#driver_bank').val(driver_bank);
        $('#driver_cmnd').val(driver_cmnd);
        $('#driver_code').val(driver_code);
        $('#driver_phone').val(driver_phone);
        $('#vehicle_number').val(vehicle_number);
        $("#vehicle option:contains(" + vehicle_number + ")").attr('selected', 'selected');
        
        $('#start_work').val(start_work.replace(/\//g,"-"));
        $('#end_work').val(end_work.replace(/\//g,"-"));
        
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

        $('#driver_name').focus();
        $('#driver_name').val("");
        $('#driver_phone').val(0);
        $('#driver_code').val("");
        $('#driver_bank').val("");
        $('#driver_birth').val("");
        $('#driver_cmnd').val("");
        $('#driver_name').attr('data', "");

        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


}


$(document).ready(function(){
            // Validate form
            $("#add_driver").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    
                
                    var driver_name = $('#driver_name').attr('value');
                    var driver_phone = $('#driver_phone').attr('value');
                    var vehicle = $('#vehicle').attr('value');
                    var start_work = $('#start_work').attr('value');
                    var end_work = $('#end_work').attr('value');
                    var driver_code = $('#driver_code').attr('value');
                    var driver_bank = $('#driver_bank').attr('value');
                    var driver_birth = $('#driver_birth').attr('value');
                    var driver_cmnd = $('#driver_cmnd').attr('value');
                    var steersman = $('#driver_name').attr('data');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/driver/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            driver_name: driver_name,
                            driver_phone: driver_phone,
                            vehicle: vehicle,
                            start_work: start_work,
                            end_work: end_work,
                            driver_code: driver_code,
                            driver_bank: driver_bank,
                            driver_birth: driver_birth,
                            driver_cmnd: driver_cmnd,
                            steersman: steersman,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    $('#driver_name_'+yes).text(driver_name);
                                    $('#driver_phone_'+yes).text(driver_phone);
                                    $('#vehicle_number_'+yes).text($("#vehicle :selected").text());
                                    $('#start_work_'+yes).text(start_work);
                                    $('#end_work_'+yes).text(end_work);
                                }
                                
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    setTimeout(function() {
                                        sapxep('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');
                                      }, 200);
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="driver_name_'+parseInt(lastID+1)+'">'+driver_name+'</td><td class="fix" id="driver_phone_'+parseInt(lastID+1)+'">'+driver_phone+'</td><td class="fix" id="vehicle_number_'+parseInt(lastID+1)+'">'+$("#vehicle :selected").text()+'</td><td class="fix" id="start_work_'+parseInt(lastID+1)+'">'+start_work+'</td><td class="fix" id="end_work_'+parseInt(lastID+1)+'">'+end_work+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
     $('#driver_name').keyup(function(){
      
        var keyword = $(this).val();
        $.ajax({
            url: '<?php echo BASE_URL ?>/driver/getdriver',
            type: 'POST',
            data: {keyword:keyword},
            success:function(data){
                $('#vehicle_list_id').slideDown(200);
                $('#vehicle_list_id').html(data);
            }
        });
        if ($('#driver_name').val() == "" || $('#driver_name').attr('data') == "") {
            //$('#loc_from').val("");
            $('#driver_name').attr('data',"");
            $('#driver_name').attr('code',false);
        }
      
   }); 

   
   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

function set_item_driver(value,name,code,cmnd,birth,phone,bank) {
    // change input value
    $('#driver_name').val(name);
    $("#driver_name").attr("data",value);
    $("#driver_name").attr("code",'true');
    $('#driver_code').val(code);
    $('#driver_cmnd').val(cmnd);
    $('#driver_birth').val(birth);
    $('#driver_phone').val(phone);
    $('#driver_bank').val(bank);
    
    // hide proposition list
    $('#vehicle_list_id').hide();
    $('#driver_name').focus();
     
     
}
</script>

<?php } ?>

<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

    $("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:200,
            width:500,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');

var pickerOpts = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onSelect: function(dateStr) {
            var d = $.datepicker.parseDate('dd-mm-yy', dateStr);
            var years = parseInt(3, 10);

            d.setFullYear(d.getFullYear() + years);

            $('#end_work').datepicker('setDate', d);
            
        },
        onClose: function(selectedDate) {
                
                $( "#end_work" ).datepicker( "option", "minDate", selectedDate );

         },
    }; 
    $("#start_work").datepicker(pickerOpts);

    var pickerOpts2 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true,
        onClose: function(selectedDate) {
                
                $( "#start_work" ).datepicker( "option", "maxDate", selectedDate );

         },
    }; 
    $("#end_work").datepicker(pickerOpts2);


var pickerOpts3 = {
        closeText: "Đóng",
        currentText: "Hiện tại",
        nextText: "Tiếp",
        prevText: "Quay lại",
        monthNames: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        monthNamesShort: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
        dayNames: ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"],
        dayNamesShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dayNamesMin: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        yearRange: "-100:+5",
        firstDay: 1,
        isRTL: false,
        showButtonPanel: true
    }; 
    $("#driver_birth").datepicker(pickerOpts3);
</script>
</div>
<style type="text/css">
    #ui-datepicker-div{
        font-size: 13px;
    }
</style>