
<?php
$url_order = 'ASC';
if ($order_by == 'vehicle_id')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'vehicle_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';

elseif ($order_by == 'cont_number')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';



    $i = $sonews*$page-($sonews-1);

?>

<div id="loading"></div>
<div id="winpopup"></div>
<center style="clear:both;margin-bottom: -30px;"><h1> DANH SÁCH XE </h1></center>
<div id="content" style="padding:5px;">
<?php if ($_SESSION['role_logined'] != 7 ) { ?>    
<div class="add-box">
    <a class="add_button" onClick="add_click();">Thêm xe</a>
    <a class="add_button" id="import_excel" href="<?= $this->url('vehicle/import')?>">Import Excel</a>
</div>
<?php } ?>
	<div class="search-box">
        
        <input type="search" id="search-input" name="s" value="<?php echo isset($keyword)?$keyword:null; ?>" placeholder="Tìm kiếm">
        <input type="button" name="" id="search-submit" class="button-search" value="Tìm kiếm" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">
    </div>
    <div class="tablenav top">
        <div class="add-box">
            <a class="add_button" id="export_excel" href="<?= $this->url('vehicle/export')?>">Export Excel</a>
        </div>
        <?php if ($_SESSION['role_logined'] != 7 ) { ?>
    	<div class="alignleft actions">
			<select name="action" id="action">
            	<option value="-1" selected="selected">Chọn</option>
                
                <option value="delete">Xóa</option>
            </select>
            <input type="button" name="" id="doaction" class="button action" value="Áp dụng" onclick="action();">
		</div>
        <?php } ?>
		<div class="alignleft actions">
		<select name="m" id="chonloc">
			<option  value="18446744073709">Hiển thị tất cả</option>
			<option value="5">Hiển thị 5 giá trị</option>
            <option value="10">Hiển thị 10 giá trị</option>
            <option value="15">Hiển thị 15 giá trị</option>
            <option selected="selected" value="20">Hiển thị 20 giá trị</option>
		</select>
		<input type="button" name="" id="post-query-submit" class="button" value="Chọn lọc" onclick="searchall('<?php echo $page ?>','<?php echo $order_by ?>','<?php echo $order ?>');">						 		
        </div>

      </div>

</div>

<table class="table_data">
<thead>
    <tr>
    	<th  class="fix"><input type="checkbox" onclick="checkall('checkbox', this)" name="checkall"/></th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vehicle_id','<?php echo $url_order ?>')">STT <?php if ($order_by == 'vehicle_id'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','vehicle_number','<?php echo $url_order ?>')">Số xe <?php if ($order_by == 'vehicle_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_name','<?php echo $url_order ?>')">Tên tài xế <?php if ($order_by == 'driver_name'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','driver_phone','<?php echo $url_order ?>')">SĐT tài xế <?php if ($order_by == 'driver_phone'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        <th  class="fix">
            <a class="sort <?php echo $order ?>" onclick="sapxep('<?php echo $page ?>','cont_number','<?php echo $url_order ?>')">Số cont <?php if ($order_by == 'cont_number'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a>
        </th>
        
        
         <?php if ($_SESSION['role_logined'] != 7 ) { ?>  
        <th  class="fix">&nbsp;</th>
        <?php } ?>
    </tr>
    
   </thead>
   <tbody>
    <?php foreach ($vehicles as $vehicle) : ?>
        <tr onClick="HighLightTR(this,'#4d90fe','cc3333');" id="<?php echo $vehicle->vehicle_id ?>" class="edit_tr">
        	<td><input name="check[]" type="checkbox" class="checkbox" value="<?php echo $vehicle->vehicle_id ?>"></td>
            <td class="fix"><?php echo $i++; ?></td>
            
            <td class="fix" id="vehicle_number_<?php echo $vehicle->vehicle_id; ?>"><?php echo $vehicle->vehicle_number; ?></td>
            <td class="fix" id="driver_name_<?php echo $vehicle->vehicle_id; ?>"><?php echo isset($driver_data[$vehicle->vehicle_id]['driver_name'])?$driver_data[$vehicle->vehicle_id]['driver_name']:null; ?></td>
            <td class="fix" id="driver_phone_<?php echo $vehicle->vehicle_id; ?>"><?php echo isset($driver_data[$vehicle->vehicle_id]['driver_phone'])?$driver_data[$vehicle->vehicle_id]['driver_phone']:null; ?></td>
            <td class="fix" id="cont_number_<?php echo $vehicle->vehicle_id; ?>"><?php echo $vehicle->cont_number; ?></td>
            <td class="fix" style="display:none" id="vehicle_type_<?php echo $vehicle->vehicle_id; ?>"><?php echo $vehicle->vehicle_type; ?></td>
            <?php if ($_SESSION['role_logined'] != 7 ) { ?>
            <td>
                <a class="error" href="#">Sửa</a>
                | 
                <a class="error" onclick="del(<?php echo $vehicle->vehicle_id ?>)" >Xóa</a>
            </td>
            <?php } ?>
        </tr>
    <?php endforeach; ?>
   </tbody>
</table>
<?php
$this->helper('slidePaginator');
?>

<div id="error" class="error"><?php echo isset($error) ? $error : null; ?></div>

<div class="add-field">
        <fieldset class="groupbox">
            <legend>
                <span><h3>Thông tin xe </h3></span>
            </legend>
            <div class="login_body">
                  <form id="add_vehicle" method="post" action="">
                      <table style="margin:0px auto;width:60%">
                        <tr>
                            
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td></td>
                            <td>&nbsp;</td>
                            <td><div class="add-box"><a class="add_button" onClick="add_click();">Thêm xe</a></div></td>
                            
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td>Số xe </td>
                            <td>
                                <input type="text"  id="vehicle_number" name="vehicle_number" tabindex="1" required="required">
                            </td>
                            <td>Số cont </td>
                            <td><input type="text" id="cont_number"  name="cont_number" tabindex="2" ></td>
                            <td>Loại </td>
                            <td>
                                <select id="vehicle_type" name="vehicle_type" tabindex="3">
                                    <option value="1">Mới</option>
                                    <option value="2">Thuê</option>
                                    <option value="3">Cũ</option>
                                </select>
                            </td>
                            

                        </tr>
                        
                        
                        
                        
                        <tr>
                            <td>&nbsp;</td>
                            <td><input type="hidden" readonly id="yes" name="yes" required="required" ></td>
                            <td>&nbsp;</td>
                        </tr>
                        
                        
                         <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><input type="submit" name="submit" value="Hoàn tất" tabindex="4"></td>
                            <td ><input type="reset" name="reset" value="Nhập lại" tabindex="5"></td>
                            <td></td>
                            <td></td>
                             
                        </tr>
                    </table> 
                </form>
            </div>
        </fieldset>
    </div>

<?php if ($_SESSION['role_logined'] != 7 ) { ?>
<script type="text/javascript">
$('html').click(function(e) {
    if(e.target == '[object HTMLDivElement]' || e.target == '[object HTMLBodyElement]') {
        $('.add-field').slideUp(500);    
    }
   
});
    $('.edit_tr').click(function(){
        if(!$('.checkbox').is(':checked')){
            $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);
        }
        
        var vehicle_number = $(this).find("#vehicle_number_"+$(this).attr('id')).text();
        var cont_number = $(this).find("#cont_number_"+$(this).attr('id')).text();
        var vehicle_type = $(this).find("#vehicle_type_"+$(this).attr('id')).text();
        //alert(vehicle_from);
        $('#yes').val($(this).attr('id'));
        

        $('#vehicle_number').val(vehicle_number);
        $('#cont_number').val(cont_number);
        
        $('#vehicle_type option[value='+vehicle_type+']').attr('selected','selected');
        
    });


</script>
<script type="text/javascript">

function add_click(){
    $('#yes').val("");
    $('.add-field').slideDown(500);
    $("html, body").animate({ scrollTop: $('.add-field').offset().top }, 300);

        $('#vehicle_number').focus();
        $('#vehicle_number').val("");
        $('#cont_number').val("");
        
        $('.number').focus(function(){
            if ( $(this).val() == '0') {
               $(this).val(""); 
            };
            
        });
        $('.number').blur(function(){
            if ( $(this).val() == "") {
                $(this).val(0);
            };
            
        });


}


$(document).ready(function(){
            // Validate form
            $("#add_vehicle").validate({
                errorElement: "span", // Định dạng cho thẻ HTML hiện thông báo lỗi
                rules: {
                    
                },
                submitHandler: function(form) {
                
                    
                    var vehicle_number = $('#vehicle_number').attr('value');
                    var cont_number = $('#cont_number').attr('value');
                    var vehicle_type = $('#vehicle_type').attr('value');
                    
                    var yes = $('#yes').attr('value');
                    
                    var action      = "them";
                 
                    $.ajax({
                        type: "POST", // phương thức gởi đi
                        url: "<?php echo BASE_URL ?>/vehicle/add", // nơi mà dữ liệu sẽ chuyển đến khi submit
                        data: {
                            vehicle_number: vehicle_number,
                            cont_number: cont_number,
                            vehicle_type: vehicle_type,
                            yes: yes,
                            }, // giá trị post
                        success: function(answer){ // if everything goes well
                            $('#error').hide();
                            $('#error').slideToggle(100); // hiển thị thẻ div success
                            $('#error').html('<div class="successbox">'+answer+'</div>'); // đặt kết quả trả về từ test.php vào thẻ div success
                            $('#error').fadeOut(10000);

                            if (yes != "") {
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    $('#vehicle_number_'+yes).text(vehicle_number);
                                    $('#cont_number_'+yes).text(cont_number);
                                }
                                
                            }
                            else{
                                if (answer.trim() != "Thông tin này đã tồn tại") {
                                    var lastID = parseInt($('#lasted').html());
                                    var rowCount = parseInt($('.table_data > tbody > tr').length);
                                    $('.table_data > tbody:last')
                                    .append(
                                        '<tr onclick="HighLightTR(this,"#4d90fe","cc3333");" id="'+parseInt(lastID+1)+'" class="edit_tr"><td><input name="check[]" type="checkbox" class="checkbox" value="'+parseInt(lastID+1)+'"></td><td class="fix">'+parseInt(rowCount+1)+'</td><td class="fix" id="vehicle_number_'+parseInt(lastID+1)+'">'+vehicle_number+'</td><td class="fix" id="driver_name_'+parseInt(lastID+1)+'"></td><td class="fix" id="driver_phone_'+parseInt(lastID+1)+'"></td><td class="fix" id="cont_number_'+parseInt(lastID+1)+'">'+cont_number+'</td><td><a class="error" href="#">Sửa</a> | <a class="error" onclick="del('+parseInt(lastID+1)+')">Xóa</a></td></tr>'
                                    );

                                    $('#lasted').html(parseInt(lastID+2));
                                }
                            }
                        }
                    });
                    return false;
                     
                 }
            });
   
   
   

   
   $('.number').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9-.]/g, "")
          .replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        ;
      });
    });
   $('.numbers').keyup(function(event) {

          // skip for arrow keys
      if(event.which >= 37 && event.which <= 40) return;

      // format number
      $(this).val(function(index, value) {
        return value
          .replace(/[^0-9]/g, "")
          .replace(/(\d{3})(\d{3})(\d{4})/, "$1 $2 $3")
        ;
      });
    });
    

});
function get_number(id){
    return $(id).val().replace(/\,/g,'');
}

</script>
<?php } ?>

<div style="display:none" id="lasted"></div>
<script type="text/javascript">
    var count = parseInt(<?php echo $lastID ?>);
    $('#lasted').html(count);

    $("#import_excel").click(function(){
        $("#winpopup").dialog({
            draggable:true,
            modal: true,
            autoOpen: false,
            height:200,
            width:500,
            resizable: false,
            title:'Import Excel',
            
        });
        $("#winpopup").load($(this).attr('href'));
        $("#winpopup").dialog("open");
         
        return false;
    });

var ch = "<?php echo $limit ?>";
$('#chonloc option[value='+ch+']').attr('selected','selected');
</script>
</div>